# Logos
logos:
  cc_by_sa: "by-sa.png"
  openai: "openai.png"
  eleven_labs: "Eleven_Labs.png"
  pbn_all_white: "all white.png"
  pbn_all_black: "all black.png"
  instructeur_photo: "instructeur.png"
  waveform: "waveform.png"

# General information for footer
pgp_key: "Plan₿ Network’s PGP: 5720 CD57 7E78 94C9 8DBD 580E 8F12 D0C6 3B1A 606E"
course_code: "BTC204"
version: "V.001"
date: "2024-08"
ia_translated_text: "IA Translated"

# Colors in RGB format
colors:
  white: [255, 255, 255]
  black: [0, 0, 0]
  orange: [255, 92, 0]

# Default languages for slides
default_languages:
  - cs
  - de
  - en
  - es
  - fi
  - fr
  - it
  - ja
  - pt
  - ru
  - vi
  - id
  - et
  - zh-hans
